package com.resume.analyzer.Services;

import com.lowagie.text.*;
import com.lowagie.text.Font;
import com.lowagie.text.pdf.PdfWriter;
import com.resume.analyzer.Model.AnalysisResult;
import lombok.extern.slf4j.Slf4j;
import org.springframework.ai.reader.ExtractedTextFormatter;
import org.springframework.ai.reader.pdf.PagePdfDocumentReader;
import org.springframework.ai.reader.pdf.config.PdfDocumentReaderConfig;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import java.io.ByteArrayOutputStream;
import java.io.IOException;

@Slf4j
@Service
public class PDFService {

    public String extractText(MultipartFile pdfFile) throws IOException {
        PagePdfDocumentReader pdfDocumentReader = new PagePdfDocumentReader(pdfFile.getResource(),
                PdfDocumentReaderConfig.builder().build());
        return pdfDocumentReader.read().toString();
    }

    public byte[] generatePrepGuide(AnalysisResult result) throws Exception {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        Document document = new Document(PageSize.A4, 50, 50, 50, 50);
        PdfWriter.getInstance(document, out);
        document.open();

        // FONTS
        Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 22);
        Font subTitleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16);
        Font bodyFont = FontFactory.getFont(FontFactory.HELVETICA, 11);

        // PAGE 1: STRATEGIC OVERVIEW
        document.add(new Paragraph("NEURAL CAREER DOSSIER: " + result.getPrimaryRole(), titleFont));
        document.add(new Paragraph("Target Alignment Score: " + result.getOverallScore() + "%", subTitleFont));
        document.add(new Paragraph("\nSTRATEGIC RECOMMENDATION:", subTitleFont));
        document.add(new Paragraph(result.getRecommendation().replaceAll("\\*", ""), bodyFont));
        document.add(new Paragraph("\n" + "=".repeat(50)));
        document.newPage();

        // PAGE 2: SKILL GAP & EVOLUTION
        document.add(new Paragraph("EVOLUTION STRATEGY & SKILL MASTERY", subTitleFont));
        document.add(new Paragraph("\nYour AI-generated 6-step roadmap for bridging the technical gap:", bodyFont));
        document.add(new Paragraph(result.getTrajectoryJson().replaceAll("[\\[\\]\"]", ""), bodyFont));
        document.add(new Paragraph("\nSTRENGTHS IDENTIFIED:", subTitleFont));
        document.add(new Paragraph(result.getStrengths().replaceAll("[\\[\\]\"]", ""), bodyFont));
        document.newPage();

        // PAGE 3: INTERVIEW PREPARATION
        document.add(new Paragraph("NEURAL INTERVIEW PREPARATION", subTitleFont));
        document.add(new Paragraph("\nCore Concepts to Master for " + result.getPrimaryRole() + ":", bodyFont));
        document.add(new Paragraph("1. Behavioral scenarios tailored to your past experience.\n" +
                "2. Technical deep-dive into identified skill gaps.\n" +
                "3. Value proposition alignment for " + result.getPrimaryRole() + ".", bodyFont));
        document.add(new Paragraph("\nWEAKNESSES TO MITIGATE:", subTitleFont));
        document.add(new Paragraph(result.getWeaknesses().replaceAll("[\\[\\]\"]", ""), bodyFont));
        document.newPage();

        // PAGE 4: LEARNING RESOURCES & REFERENCES
        document.add(new Paragraph("CURATED STUDY RESOURCES", subTitleFont));
        document.add(new Paragraph("\nClickable links for study (Generated by AI):", bodyFont));
        document.add(new Paragraph(result.getResourcesJson().replaceAll("[\\[\\]\"\\{\\}]", ""), bodyFont));
        document.add(new Paragraph("\n\nFINAL NOTE: This guide is dynamically generated based on your resume DNA. Focus on the learning links above to maximize your chances.", bodyFont));

        document.close();
        return out.toByteArray();
    }
}